// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMLI7HimPjKotWwrJiUWgxlsnJrJYvauw',
    appId: '1:784307705994:web:de0a06073754cbafcf3573',
    messagingSenderId: '784307705994',
    projectId: 'talentlink-51fb6',
    authDomain: 'talentlink-51fb6.firebaseapp.com',
    storageBucket: 'talentlink-51fb6.firebasestorage.app',
    measurementId: 'G-D761Q65W0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZm-LfFLzdWjqZImSEt4eD1QMo-q4wrqo',
    appId: '1:784307705994:android:fe8e1de3fb1bc07dcf3573',
    messagingSenderId: '784307705994',
    projectId: 'talentlink-51fb6',
    storageBucket: 'talentlink-51fb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw6uO1PmNOCphdXTgna91lXeMfWWA-tlE',
    appId: '1:784307705994:ios:52164c53cfb34267cf3573',
    messagingSenderId: '784307705994',
    projectId: 'talentlink-51fb6',
    storageBucket: 'talentlink-51fb6.firebasestorage.app',
    iosBundleId: 'com.example.talentlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw6uO1PmNOCphdXTgna91lXeMfWWA-tlE',
    appId: '1:784307705994:ios:52164c53cfb34267cf3573',
    messagingSenderId: '784307705994',
    projectId: 'talentlink-51fb6',
    storageBucket: 'talentlink-51fb6.firebasestorage.app',
    iosBundleId: 'com.example.talentlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMLI7HimPjKotWwrJiUWgxlsnJrJYvauw',
    appId: '1:784307705994:web:825e45f93dfa14e4cf3573',
    messagingSenderId: '784307705994',
    projectId: 'talentlink-51fb6',
    authDomain: 'talentlink-51fb6.firebaseapp.com',
    storageBucket: 'talentlink-51fb6.firebasestorage.app',
    measurementId: 'G-9BF2652B8M',
  );
}
